# Generated by Django 4.2.6 on 2023-10-27 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('fecha_vto_presentacion', models.DateField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio')),
            ],
            options={
                'verbose_name': 'Rendicion',
                'verbose_name_plural': 'Rendiciones',
            },
        ),
    ]
