# Generated by Django 4.2.6 on 2023-10-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rendicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_presentacion', models.DateField(blank=True, null=True)),
                ('numero_presentacion', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rendicion')),
            ],
            options={
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
    ]
