# Generated by Django 4.2.6 on 2023-10-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_presentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoRequerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_vig_desde', models.DateField()),
                ('fecha_vig_hasta', models.DateField()),
                ('obligatorio', models.BooleanField()),
                ('multicarga', models.BooleanField()),
                ('extensiones_permitidas', models.CharField(help_text='Separar con coma (,) cada extensión', max_length=200)),
            ],
            options={
                'verbose_name': 'Documento Requerido',
                'verbose_name_plural': 'Documentos Requeridos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoRendicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_rendiciones/')),
                ('documento_requerido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documentorequerido')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.presentacion')),
            ],
            options={
                'verbose_name': 'Documento de Rendicion',
                'verbose_name_plural': 'Documentos de Rendiciones',
            },
        ),
    ]
