# Generated by Django 4.2.6 on 2023-11-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documentorequerido_documentorendicion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presentacion',
            old_name='numero_presentacion',
            new_name='nro_presentacion',
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
