# Generated by Django 4.2.6 on 2023-11-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_documento_alter_presentacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='fecha_presentacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
